### PR TITLE
Classes are not testable, missing Equals and Hashcode method #14

### PR DESCRIPTION
**Pull request by hgvanpariya**
Equals and Hash code for DruidFilter

### CODE REVIEW

**Comment by GG-Zapr** [comment]
Thanks for your contribution.
Since the equals method is overridden only for parent class, it will check equals only for the field present in parent class.

Example:
```
DruidFilter selectorFilter = new SelectorFilter("Hello", "World");
DruidFilter selectorFilter1 = new SelectorFilter("Hola", "World");

Assert.assertEquals(selectorFilter, selectorFilter1);
```
This case will be passed, even though they are not equals.
We should add to all the child classes: 

`@EqualsAndHashCode(callSuper = true)`

Let me know.

**Comment by hgvanpariya** [comment]
@GG-Zapr , update in the clild classes

**Comment by hgvanpariya** [comment]
@GG-Zapr any update ?

**Comment by hgvanpariya** [comment]
@nihit-zapr : I've resolved the conflict ... Please let me know if any further changes are needed.

**Pull request merged**
