### PR TITLE
#35 Unit Test cases for Interval Filter, Bug Fix where type wasn't being …

### PR DESCRIPTION
**Pull request by gagangupt16**
…set, adding null checks in Interval Filter constructor

### CODE REVIEW

**Comment by gagangupt16** [comment]
3 things:

1. Bug Fix where type isn't being set for Interval Filter
2. Null check in Interval Filter constructor
3. Unit Test cases for the above

**Comment by nihit-zapr** [comment]
Should we have enum for Dimension?

**Comment by gagangupt16** [comment]
I don't think so. As per Druid doc, dimension is a string and it hasn't got a fixed set of values  either
http://druid.io/docs/latest/querying/filters.html.

**Comment by gagangupt16** [comment]
Issue: #35

**Pull request merged**
